import 'package:flutter/material.dart';

import '../theme_spec.dart';

const glassThemeSpec = ThemeSpec(
  id: 'glass',
  displayName: 'Glass',
  isGlass: true,
  transparentNavbarSurface: true,
  semantic: ThemeSemanticTokens(
    statusAvailable: Color(0xFF30D158),
    statusRequested: Color(0xFFBF5AF2),
    statusPending: Color(0xFFFFD60A),
    statusDownloading: Color(0xFF0A84FF),
    mediaTypeBadgeMovie: Color(0xFF0A84FF),
    mediaTypeBadgeShow: Color(0xFFBF5AF2),
  ),
  colors: ThemeColorTokens(
    background: Color(0xCC07090F),
    onBackground: Color(0xFFFFFFFF),
    surface: Color(0xD90E1117),
    onSurface: Color(0xFFFFFFFF),
    surfaceVariant: Color(0x29FFFFFF),
    scrim: Color(0x99060810),
    accent: Color(0xFF0A84FF),
    onAccent: Color(0xFFFFFFFF),
    buttonNormal: Color(0x1FFFFFFF),
    buttonFocused: Color(0xF2FFFFFF),
    buttonDisabled: Color(0x14FFFFFF),
    buttonActive: Color(0x3DFFFFFF),
    onButtonNormal: Color(0xFFFFFFFF),
    onButtonFocused: Color(0xFF0A0A12),
    onButtonDisabled: Color(0x66FFFFFF),
    inputBackground: Color(0x1FFFFFFF),
    inputFocused: Color(0x33FFFFFF),
    inputBorder: Color(0x33FFFFFF),
    inputBorderFocused: Color(0xFF0A84FF),
    rangeTrack: Color(0x33FFFFFF),
    rangeProgress: Color(0xFF0A84FF),
    rangeThumb: Color(0xFFFFFFFF),
    seekbarBuffered: Color(0x80FFFFFF),
    badgeBackground: Color(0xCC0A84FF),
    onBadge: Color(0xFFFFFFFF),
    badgeUnplayed: Color(0xFF0A84FF),
    badgeWatched: Color(0xFF30D158),
    recordingActive: Color(0xFFFF453A),
    recordingScheduled: Color(0xFFFF9F0A),
  ),
  borders: ThemeBorderTokens(
    cardBorder: BorderSide(color: Color(0x29FFFFFF), width: 1),
    chipBorder: BorderSide(color: Color(0x3DFFFFFF), width: 1),
    focusBorder: BorderSide(color: Color(0xFFFFFFFF), width: 2),
    navBorder: BorderSide(color: Color(0x1FFFFFFF), width: 1),
    cardRadius: BorderRadius.all(Radius.circular(14)),
    chipRadius: BorderRadius.all(Radius.circular(999)),
    chipBackground: Color(0x1FFFFFFF),
    focusGlow: [
      BoxShadow(color: Color(0x40FFFFFF), blurRadius: 12),
      BoxShadow(color: Color(0x330A84FF), blurRadius: 22, spreadRadius: 1),
    ],
  ),
);
