import 'package:flutter/material.dart';
import 'package:material_symbols_icons/symbols.dart';

/// Maps the Achievement Badges plugin's icon names to Flutter icons.
///
/// The plugin stores a Material Icons ligature name per badge, quest and rank
/// tier. Flutter tree-shakes its icon font, so a name can't be looked up at
/// runtime and every icon a badge can carry has to be named here. Admins can
/// author badges with arbitrary names, so anything unknown falls back to the
/// same trophy the plugin's own web UI falls back to.
///
/// A few come from Material Symbols, the newer set, because the font Flutter
/// bundles has no glyph for them at all.
const Map<String, IconData> _achievementIcons = <String, IconData>{
  'ac_unit': Icons.ac_unit,
  'alarm': Icons.alarm,
  'album': Icons.album,
  'all_inclusive': Icons.all_inclusive,
  'archive': Icons.archive,
  'audiotrack': Icons.audiotrack,
  'auto_awesome': Icons.auto_awesome,
  'auto_awesome_motion': Icons.auto_awesome_motion,
  'auto_fix_high': Icons.auto_fix_high,
  'auto_stories': Icons.auto_stories,
  'av_timer': Icons.av_timer,
  'award_star': Icons.star,
  'beach_access': Icons.beach_access,
  'bed': Icons.bed,
  'bedtime': Icons.bedtime,
  'block': Icons.block,
  'blur_circular': Icons.blur_circular,
  'blur_on': Icons.blur_on,
  'bolt': Icons.bolt,
  'book': Icons.book,
  'brightness_5': Icons.brightness_5,
  'cabin': Icons.cabin,
  'cake': Icons.cake,
  'calendar_month': Icons.calendar_month,
  'calendar_today': Icons.calendar_today,
  'calendar_view_week': Icons.calendar_view_week,
  'castle': Icons.castle,
  'category': Icons.category,
  'celebration': Icons.celebration,
  'chair': Icons.chair,
  'check_circle': Icons.check_circle,
  'checkroom': Icons.checkroom,
  'cloud': Icons.cloud,
  'code': Icons.code,
  'collections_bookmark': Icons.collections_bookmark,
  'connected_tv': Icons.connected_tv,
  'contrast': Icons.contrast,
  'crop_square': Icons.crop_square,
  'crown': Symbols.crown,
  'dark_mode': Icons.dark_mode,
  'date_range': Icons.date_range,
  'devices': Icons.devices,
  'diamond': Icons.diamond,
  'directions_run': Icons.directions_run,
  'diversity_3': Icons.diversity_3,
  'draw': Icons.draw,
  'eco': Icons.eco,
  'egg': Icons.egg,
  'emoji_events': Icons.emoji_events,
  'emoji_nature': Icons.emoji_nature,
  'event': Icons.event,
  'event_available': Icons.event_available,
  'event_repeat': Icons.event_repeat,
  'face': Icons.face,
  'fastfood': Icons.fastfood,
  'favorite': Icons.favorite,
  'festival': Icons.festival,
  'flag': Icons.flag,
  'flash_on': Icons.flash_on,
  'flight_takeoff': Icons.flight_takeoff,
  'gavel': Icons.gavel,
  'graphic_eq': Icons.graphic_eq,
  'grid_view': Icons.grid_view,
  'groups': Icons.groups,
  'headphones': Icons.headphones,
  'help': Icons.help,
  'history': Icons.history,
  'history_toggle_off': Icons.history_toggle_off,
  'home': Icons.home,
  'hourglass_bottom': Icons.hourglass_bottom,
  'hourglass_full': Icons.hourglass_full,
  'hourglass_top': Icons.hourglass_top,
  'insights': Icons.insights,
  'inventory_2': Icons.inventory_2,
  'language': Icons.language,
  'library_books': Icons.library_books,
  'library_music': Icons.library_music,
  'light_mode': Icons.light_mode,
  'live_tv': Icons.live_tv,
  'local_fire_department': Icons.local_fire_department,
  'local_library': Icons.local_library,
  'local_movies': Icons.local_movies,
  'lunch_dining': Icons.lunch_dining,
  'memory': Icons.memory,
  'menu_book': Icons.menu_book,
  'mic': Icons.mic,
  'military_tech': Icons.military_tech,
  'mood': Icons.mood,
  'movie': Icons.movie,
  'movie_creation': Icons.movie_creation,
  'movie_filter': Icons.movie_filter,
  'museum': Icons.museum,
  'music_note': Icons.music_note,
  'nightlife': Icons.nightlife,
  'nightlight': Icons.nightlight,
  'nights_stay': Icons.nights_stay,
  'ondemand_video': Icons.ondemand_video,
  'owl': Symbols.owl,
  'paid': Icons.paid,
  'palette': Icons.palette,
  'park': Icons.park,
  'person': Icons.person,
  'phone_iphone': Icons.phone_iphone,
  'play_circle': Icons.play_circle,
  'playlist_play': Icons.playlist_play,
  'podcasts': Icons.podcasts,
  'psychology': Icons.psychology,
  'public': Icons.public,
  'queue_music': Icons.queue_music,
  'radio': Icons.radio,
  'record_voice_over': Icons.record_voice_over,
  'redeem': Icons.redeem,
  'repeat': Icons.repeat,
  'repeat_on': Icons.repeat_on,
  'replay': Icons.replay,
  'replay_circle_filled': Icons.replay_circle_filled,
  'restaurant': Icons.restaurant,
  'rocket_launch': Icons.rocket_launch,
  'schedule': Icons.schedule,
  'science': Icons.science,
  'shopping_basket': Icons.shopping_basket,
  'spa': Icons.spa,
  'speaker_group': Icons.speaker_group,
  'speed': Icons.speed,
  'sports_esports': Icons.sports_esports,
  'sports_martial_arts': Icons.sports_martial_arts,
  'sports_score': Icons.sports_score,
  'sprout': Icons.eco,
  'stadia_controller': Icons.sports_esports,
  'stairs': Icons.stairs,
  'star': Icons.star,
  'stars': Icons.stars,
  'sunny': Icons.sunny,
  'swap_horiz': Icons.swap_horiz,
  'theater_comedy': Icons.theater_comedy,
  'theaters': Icons.theaters,
  'thumb_down': Icons.thumb_down,
  'timeline': Icons.timeline,
  'timer': Icons.timer,
  'today': Icons.today,
  'translate': Icons.translate,
  'travel_explore': Icons.travel_explore,
  'trending_up': Icons.trending_up,
  'tune': Icons.tune,
  'tv': Icons.tv,
  'umbrella': Icons.umbrella,
  'update': Icons.update,
  'verified': Icons.verified,
  'videocam': Icons.videocam,
  'videogame_asset': Icons.videogame_asset,
  'visibility': Icons.visibility,
  'waves': Icons.waves,
  'wb_incandescent': Icons.wb_incandescent,
  'wb_sunny': Icons.wb_sunny,
  'wb_twilight': Icons.wb_twilight,
  'weekend': Icons.weekend,
  'whatshot': Icons.whatshot,
  'workspace_premium': Icons.workspace_premium,
};

/// The icon for [name], or a trophy when the name is unknown or empty.
IconData achievementIcon(String? name) {
  final key = (name ?? '').trim().toLowerCase();
  return _achievementIcons[key] ?? Icons.emoji_events;
}
